# Generated by Django 4.2.7 on 2023-11-07 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cinema",
            fields=[
                ("cinema", models.AutoField(primary_key=True, serialize=False)),
                ("cinema_name", models.CharField(max_length=50)),
                ("phoneno", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("movie", models.AutoField(primary_key=True, serialize=False)),
                ("movie_name", models.CharField(max_length=50)),
                ("movie_trailer", models.URLField()),
                ("movie_rdate", models.DateField()),
                ("movie_des", models.TextField()),
                ("movie_rating", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "movie_poster",
                    models.ImageField(
                        default="movies/poster/not.jpg", upload_to="movies/poster"
                    ),
                ),
                (
                    "movie_genre",
                    models.CharField(
                        default="Action | Comedy | Romance", max_length=50
                    ),
                ),
                (
                    "movie_duration",
                    models.CharField(default="2hr 45min", max_length=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shows",
            fields=[
                ("shows", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.TimeField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("price", models.IntegerField()),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cinema_show",
                        to="accounts.cinema",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_show",
                        to="accounts.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("useat", models.CharField(max_length=100)),
                ("len1", models.IntegerField(default=0)),
                (
                    "shows",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.shows"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
